version: '3'
services:
  wadownload:
    image: whatnano
    container_name: whatnano
    volumes:
      - ./media:/home/node/app/media  # Replace the host directory path with the desired media files location
      - ./session:/home/node/app/session  # Replace the host directory path with the desired session location
    restart: unless-stopped
    init: true
    cap_add:
      - SYS_ADMIN
